// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1qHpddDRuCLgMIWIW1m605h8I1sD8JY',
    appId: '1:1099077491537:web:a78bf94cc74c8d2e669170',
    messagingSenderId: '1099077491537',
    projectId: 'flutter-eproject-50834',
    authDomain: 'flutter-eproject-50834.firebaseapp.com',
    storageBucket: 'flutter-eproject-50834.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB79uQoJAC3zjMPi9OdkdEjft5EMa9oJlc',
    appId: '1:1099077491537:android:95560796e66d4eac669170',
    messagingSenderId: '1099077491537',
    projectId: 'flutter-eproject-50834',
    storageBucket: 'flutter-eproject-50834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF27Kbh0ic-KdXpqu8i2C9wdlqam6ZK50',
    appId: '1:1099077491537:ios:3d8cc6814d22e881669170',
    messagingSenderId: '1099077491537',
    projectId: 'flutter-eproject-50834',
    storageBucket: 'flutter-eproject-50834.firebasestorage.app',
    iosBundleId: 'com.example.flutterEproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF27Kbh0ic-KdXpqu8i2C9wdlqam6ZK50',
    appId: '1:1099077491537:ios:3d8cc6814d22e881669170',
    messagingSenderId: '1099077491537',
    projectId: 'flutter-eproject-50834',
    storageBucket: 'flutter-eproject-50834.firebasestorage.app',
    iosBundleId: 'com.example.flutterEproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl1qHpddDRuCLgMIWIW1m605h8I1sD8JY',
    appId: '1:1099077491537:web:83a2fefc1e19827f669170',
    messagingSenderId: '1099077491537',
    projectId: 'flutter-eproject-50834',
    authDomain: 'flutter-eproject-50834.firebaseapp.com',
    storageBucket: 'flutter-eproject-50834.firebasestorage.app',
  );
}
