/// List of major cities in Pakistan
const List<String> pakistanCities = [
  'Islamabad',
  'Rawalpindi',
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Multan',
  'Hyderabad',
  'Peshawar',
  'Quetta',
  'Sargodha',
  'Sialkot',
  'Sukkur',
  'Gujranwala',
  'Gujrat',
  'Sheikhupura',
  'Jhang',
  'Okara',
  'Sahiwal',
  'Gwadar',
  'Mirpur Khas',
  'Bahawalpur',
  'Mingora',
  'Mardan',
  'Kohat',
  'Bannu',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Mansehra',
  'Abbottabad',
  'Haripur',
  'Gilgit',
  'Skardu',
  'Wazirabad',
  'Chiniot',
  'Hafizabad',
  'Mandi Bahauddin',
  'Narowal',
  'Kasur',
  'Chunian',
  'Vihari',
  'Khanewal',
  'Toba Tek Singh',
  'Jaranwala',
  'Samundri',
  'Tandlianwala',
  'Chichawatni',
  'Burewala',
  'Arifwala',
  'Khushab',
  'Mianwali',
  'Chakwal',
  'Jhelum',
  'Mirpur (AJK)',
  'Muzaffarabad',
  'Rawalakot',
  'Attock',
  'Murree',
  'Naran',
  'Kaghan',
  'Kalam',
];